import '@/app/globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import React, {Suspense} from "react";
import Provider from "@/app/context/client-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOption";
import Loading from "@/app/(main)/loading";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Login - Single Sign On',
  // description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider session={session} >
        <StyledComponentsRegistry>
            <Suspense fallback={<Loading/>}>
                {
                    children
                }
            </Suspense>
        </StyledComponentsRegistry>
      </Provider>
      </body>
    </html>
  )
}
